server:
  port: 8081
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
    #指定服务的上下文路径
    #context-path: /im-chat

spring:
  application:
    name: im-chat
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/im-chat?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: root
    password: 12345678

  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

mybatis-plus:
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
    map-underscore-to-camel-case: false
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # mapper
  mapper-locations:
    # *.xml的具体路径
    - classpath*:mapper/*.xml
minio:
  url: http://127.0.0.1:6002  #内网地址
  externalUrl: http://127.0.0.1:6002 #外网访问地址
  accessKey: admin
  secretKey: admin
  bucketName: im-chat
  imagePath: image
  filePath: file
  videoPath: video


jwt:
  authorization:
    expireIn: 1800
    secret: HpOoQsbqKwpQ
  refreshToken:
    expireIn: 604800
    secret: HpOoQsbqKwpQ

# swagger配置
swagger:
  title: 系统模块接口文档
  license: Powered By xxx
  licenseUrl: https://xxx.vip
  version: 1.0