server:
  port: 8877

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0

websocket:
  enable: true
  port: 8878

tcpsocket:
  enable: false # 暂时不开启
  port: 8879

jwt:
  authorization:
    secret: MIIBIjANBgkq  # 跟im-platfrom的secret必须一致